export const path = {
  products: '/product',
  home: '/',
  login: '/login',
  register: '/register',
  order: 'user/order',
  logout: '/logout',
  admin: '/admin',
  productDetail: '/product/:productId',
  blogDetail: '/blog/:blogId',
  cart: '/cart',
  payment: '/payment',
  blog: '/blog',
  contact: '/contact',
  adminProduct: '/admin/products',
  thankYou: '/thankyou',
  adminBlog: '/admin/blogs',
  adminBrand: '/admin/brands',
  adminCategory: '/admin/categories',
  adminUser: '/admin/users',
  adminOrder: '/admin/orders',
  adminBanner: '/admin/banners',
  profile: '/user/profile'
} as const
